---
- name: Login to container registry
  kayobe_container_login:
    registry_url: "{{ kolla_docker_registry or omit }}"
    username: "{{ kolla_docker_registry_username }}"
    password: "{{ kolla_docker_registry_password }}"
    reauthorize: yes
  when:
    - deploy_containers_registry_attempt_login | bool
  become: "{{ container_engine == 'podman' }}"

- name: Deploy containers (loop)
  include_tasks: deploy-container.yml
  vars:
    container_name: "{{ item.key }}"
    container_config: "{{ item.value }}"
  with_dict: "{{ seed_containers }}"
