---
- name: Return artifact to Zuul
  zuul_return:
    data:
      zuul:
        artifacts:
          - name: "Unit Test Report"
            url: "{{ inventory_hostname }}/test-results.html"
            metadata:
              type: unit_test_report

- name: Run testinfra tests
  command: >-
    {{ host_configure_testinfra_venv }}/bin/py.test
    {{ host_configure_test_path }}
    --html={{ host_configure_test_results_path }}
    --self-contained-html
  environment:
    SITE_MIRROR_FQDN: "{{ host_configure_site_mirror_fqdn }}"
