---
# Whether to add entries to /etc/hosts.
customize_etc_hosts: true

# List of hosts to add to /etc/hosts.
etc_hosts_hosts: []

# Which network to use for host entries in /etc/hosts
etc_hosts_network: "{{ undef() }}"

# Dictionary of custom /etc/hosts entries.
# Each key is added as a hostname,
# Each value is added as an IP.
custom_etc_hosts_entries: {}
