---
collections:
  - name: https://opendev.org/openstack/ansible-collection-kolla
    type: git
    version: stable/2025.1
  - name: community.docker
    version: 3.11.0
  - name: dellemc.os10
    version: 1.1.1
  - name: nvidia.nvue
    version: 1.2.6
  - name: openstack.cloud
    version: '<3'
  - name: stackhpc.linux
    version: 1.3.4
  - name: stackhpc.network
    version: 1.0.0
  - name: stackhpc.openstack
    version: 0.2.2

roles:
  - src: ahuffman.resolv
    version: 1.3.1
  - src: giovtorres.tuned
    version: 1.1.1
  - src: jriguera.configdrive
    # There are no versioned releases of this role.
    version: 71ddface5540ee0ff9e35bcc4334c766ed5d5d3f
  - src: MichaelRigart.interfaces
    version: v1.15.6
  - src: mrlesmithjr.chrony
    version: v0.1.6
  - src: mrlesmithjr.manage_lvm
    version: v0.2.8
  - src: mrlesmithjr.mdadm
    version: v0.1.1
  - src: singleplatform-eng.users
    version: v1.2.5
  - src: stackhpc.drac
    version: 1.1.6
  - src: stackhpc.drac-facts
    version: 1.0.0
  - src: stackhpc.libvirt-host
    version: v1.14.0
  - src: stackhpc.libvirt-vm
    version: v1.16.3
  - src: stackhpc.luks
    version: 0.4.2
  - src: stackhpc.os-ironic-state
    version: v1.3.1
  - src: stackhpc.timezone
    version: 1.2.2
