---
- src: ahuffman.resolv
  version: 1.3.1
- src: jriguera.configdrive
  # There are no versioned releases of this role.
  version: 6b5f1d55bc3f27fa2855d8dd59b5c224d160d806
- src: MichaelRigart.interfaces
  version: v1.2.0
- src: mrlesmithjr.manage-lvm
  version: v0.1.4
- src: resmo.ntp
  version: 0.4.0
- src: singleplatform-eng.users
  version: v1.2.5
- src: stackhpc.dell-powerconnect-switch
  version: v1.0.0
- src: stackhpc.drac
  version: 1.1.4
- src: stackhpc.drac-facts
  version: 1.0.0
- src: stackhpc.grafana-conf
  version: 1.1.0
- src: stackhpc.libvirt-host
  version: v1.3.0
- src: stackhpc.libvirt-vm
  version: v1.6.0
- src: stackhpc.mellanox-switch
  version: v1.0.0
- src: stackhpc.os-images
  version: v1.4.0
- src: stackhpc.os-ironic-state
  version: v1.1.0
- src: stackhpc.os-networks
  version: v1.1.0
- src: stackhpc.os-openstackclient
  version: v1.3.0
- src: stackhpc.os-shade
  version: v1.3.0
# We are currently using a fork of this role since the upstream yatesr.timezone
# role includes symlinks which do not play nicely with PBR. Once that issue has
# been resolved in PBR, we can revert to using the upstream yatesr.timezone
# role.
- src: stackhpc.timezone
  version: 1.2.0
