---
collections:
  - name: https://opendev.org/openstack/ansible-collection-kolla
    type: git
    version: unmaintained/2023.1
  - name: dellemc.os10
    version: 1.1.1

roles:
  - src: ahuffman.resolv
    version: 1.3.1
  - src: stackhpc.systemd_networkd
    version: v1.0.6
  - src: giovtorres.tuned
    version: 1.1.0
  - src: jriguera.configdrive
    # There are no versioned releases of this role.
    version: 29871bf3279ef95fc8f7339b9abd13f869980750
  - src: MichaelRigart.interfaces
    version: v1.14.4
  - src: mrlesmithjr.chrony
    version: v0.1.4
  - src: mrlesmithjr.manage_lvm
    version: v0.2.8
  - src: mrlesmithjr.mdadm
    version: v0.1.1
  - src: singleplatform-eng.users
    version: v1.2.5
  - src: stackhpc.dell-powerconnect-switch
    version: v1.1.0
  - src: stackhpc.drac
    version: 1.1.6
  - src: stackhpc.drac-facts
    version: 1.0.0
  - src: stackhpc.grafana-conf
    version: 1.1.1
  - src: stackhpc.libvirt-host
    version: v1.12.1
  - name: stackhpc.libvirt-vm
    version: v1.16.1
  - src: stackhpc.luks
    version: 0.4.2
  - src: stackhpc.mellanox-switch
    version: v1.0.0
  - src: stackhpc.os-images
    version: v1.16.0
  - src: stackhpc.os-ironic-state
    version: v1.3.1
  - src: stackhpc.os-networks
    version: v1.5.3
  - src: stackhpc.os-openstackclient
    version: v1.5.0
  - src: stackhpc.os_openstacksdk
    version: v1.3.0
  - src: stackhpc.timezone
    version: 1.2.1
