---
- src: ahuffman.resolv
- src: jriguera.configdrive
- src: MichaelRigart.interfaces
- src: mrlesmithjr.manage-lvm
- src: resmo.ntp
#- src: singleplatform-eng.users
- src: https://github.com/stackhpc/ansible-users
  version: append
  name: singleplatform-eng.users
- src: stackhpc.dell-powerconnect-switch
- src: stackhpc.drac
- src: stackhpc.drac-facts
- src: stackhpc.grafana-conf
- src: stackhpc.libvirt-host
- src: stackhpc.libvirt-vm
- src: stackhpc.os-flavors
- src: stackhpc.os-images
- src: stackhpc.os-ironic-state
- src: stackhpc.os-networks
- src: stackhpc.os-openstackclient
- src: stackhpc.os-projects
- src: stackhpc.os-shade
- src: yatesr.timezone
