---
collections:
  - name: https://opendev.org/openstack/ansible-collection-kolla
    type: git
    version: master
  - name: community.docker
    version: 3.11.0
  - name: dellemc.os10
    version: 1.1.1
  - name: nvidia.nvue
    version: 1.2.6
  - name: openstack.cloud
    version: '<3'
  - name: stackhpc.linux
    version: 1.3.0
  - name: stackhpc.network
    version: 1.0.0
  - name: stackhpc.openstack
    version: 0.2.2

roles:
  - src: ahuffman.resolv
    version: 1.3.1
  - src: giovtorres.tuned
    version: 1.1.1
  - src: jriguera.configdrive
    # There are no versioned releases of this role.
    version: acd08fd126d0e442ab8b3bc518e37761390d8c2f
  - src: MichaelRigart.interfaces
    version: v1.15.3
  - src: mrlesmithjr.chrony
    version: v0.1.4
  - src: mrlesmithjr.manage_lvm
    version: v0.2.8
  - src: mrlesmithjr.mdadm
    version: v0.1.1
  - src: singleplatform-eng.users
    version: v1.2.5
  - src: stackhpc.drac
    version: 1.1.6
  - src: stackhpc.drac-facts
    version: 1.0.0
  - src: stackhpc.libvirt-host
    version: v1.12.1
  - src: stackhpc.libvirt-vm
    version: v1.16.2
  - src: stackhpc.luks
    version: 0.4.2
  - src: stackhpc.os-ironic-state
    version: v1.3.1
  - src: stackhpc.timezone
    version: 1.2.2
