---
collections:
  - name: https://opendev.org/openstack/ansible-collection-kolla
    type: git
    version: master
  - name: community.docker
    version: 5.0.5
  - name: community.network
    version: 5.1.0
  - name: dellemc.os6
    version: 1.0.7
  - name: dellemc.os9
    version: 1.0.4
  - name: dellemc.os10
    version: 1.2.7
  - name: nvidia.nvue
    version: 1.2.9
  - name: openstack.cloud
    version: '<3'
  - name: stackhpc.linux
    version: 1.5.1
  - name: stackhpc.network
    version: 1.0.0
  - name: stackhpc.openstack
    version: 0.9.0

roles:
  - src: ahuffman.resolv
    version: 1.3.2
  - src: giovtorres.tuned
    version: 2.0.2
  - src: git+https://github.com/stackhpc/ansible-role-configdrive.git
    name: jriguera.configdrive
    version: fb199247333e72e38a9d414cf7b6144daa645477
  - src: MichaelRigart.interfaces
    version: v1.16.1
  - src: mrlesmithjr.chrony
    version: v0.1.6
  - src: mrlesmithjr.manage_lvm
    version: v0.2.13
  - src: mrlesmithjr.mdadm
    version: v0.1.9
  - src: singleplatform-eng.users
    version: v1.2.6
  - src: stackhpc.drac
    version: 1.1.6
  - src: stackhpc.drac-facts
    version: v1.0.1
  - src: stackhpc.libvirt-host
    version: v1.15.0
  - src: stackhpc.libvirt-vm
    version: v1.16.3
  - src: stackhpc.luks
    version: 0.4.4
  - src: stackhpc.os-ironic-state
    version: v1.3.1
  - src: stackhpc.timezone
    version: 1.2.2
