#!/usr/bin/env bash

CONTAINER_ENGINE="docker"

if sudo podman inspect openvswitch_vswitchd >/dev/null 2>&1; then
    CONTAINER_ENGINE="podman"
fi

sudo ${CONTAINER_ENGINE} exec openvswitch_vswitchd ovs-vsctl "$@"
