---
# This file holds the config given to Tenks when running `tenks-deploy.sh`. It
# assumes the existence of the bridge `breth1`.

node_types:
  type0:
    memory_mb: 3072
    vcpus: 1
    volumes:
      # There is a minimum disk space capacity requirement of 4GiB when using Ironic Python Agent:
      # https://github.com/openstack/ironic-python-agent/blob/master/ironic_python_agent/utils.py#L290
      # The CentOS8 cloud image seems to fill a 4GiB disk, so allow 6.
      - capacity: 6GiB
    physical_networks:
      - physnet1
    console_log_enabled: true
    # We seem to hit issues with missing cpu features in CI as a result of using host-model, e.g:
    # https://zuul.opendev.org/t/openstack/build/02c33ab51664419a88a5a54ad22852a9/log/primary/system_logs/libvirt/qemu/tk0.txt.gz#38
    cpu_mode:

specs:
  - type: type0
    count: 1
    ironic_config:
      resource_class: test-rc
      network_interface: noop

node_name_prefix: controller

nova_flavors: []

physnet_mappings:
  physnet1: breth1

bridge_type: linuxbridge

default_boot_mode: "bios"

# No placement service.
wait_for_placement: false

# Nested virtualisation is not working well in CI currently. Force the use of
# QEMU.
libvirt_vm_engine: "qemu"
