---
- name: Force time synchronisation
  become: True
  block:
    - name: Configure burst
      command: chronyc 'burst 4/4'

    - name: Step the clock
      command: chronyc makestep

    - name: Wait before hardware clock synchronisation
      pause:
        seconds: 5

    - name: Ensure hwclock is installed
      package:
        name: "{{ 'util-linux' if ansible_facts.os_family == 'RedHat' else 'util-linux-extra' }}"
        state: present

    - name: Force hardware clock synchronisation
      command: hwclock --systohc
  when: ntp_force_sync | bool
