---
- name: Ensure dnf.conf configuration exists
  ini_file:
    path: /etc/dnf/dnf.conf
    section: "main"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ query('dict', dnf_config) }}"
  become: true

- name: Configure local mirror
  include_tasks: local-mirror.yml
  when: dnf_use_local_mirror | bool

- import_tasks: custom-repo.yml

- name: Configure repository overrides
  become: true
  community.general.dnf_config_manager:
    name: "{{ item }}"
    state: "{{ dnf_repo_state_overrides[item] }}"
  # NOTE(wszumski): Ignore repos managed with dnf_custom_repos as enabled state
  # is set in definition.
  loop: "{{ dnf_repo_state_overrides.keys() | difference(dnf_custom_repos.keys()) }}"
