---
# Action to perform: One of: "deploy", "destroy".
manage_containers_action: "deploy"

#TODO(mattcrees): remove deploy_containers_defaults in Hibiscus cycle
manage_containers_defaults: "{{ deploy_containers_defaults }}"

deploy_containers_defaults:
  comparisons:
    image: strict
    env: strict
    volumes: strict
  detach: True
  network_mode: "host"
  init: True
  privileged: False
  restart_policy: "unless-stopped"

manage_custom_containers: []

#TODO(mattcrees): remove deploy_containers_docker_api_timeout in Hibiscus cycle.
manage_containers_docker_api_timeout: "{{ deploy_containers_docker_api_timeout | default(120) }}"

manage_containers_registry:
manage_containers_registry_username:
manage_containers_registry_password:

manage_containers_registry_attempt_login: "{{ manage_containers_registry_username is truthy and manage_containers_registry_password is truthy }}"
