---
- hosts: primary
  environment:
    KAYOBE_CONFIG_SOURCE_PATH: "{{ kayobe_config_src_dir }}"
  tasks:
    - name: Prevent NetworkManager from managing default interface
      command: 'nmcli dev set {{ ansible_facts.default_ipv4.interface }} managed no'
      become: true
      when: ansible_facts.os_family == 'RedHat'

    - name: Ensure Ansible control host is configured
      shell:
        cmd: "{{ kayobe_src_dir }}/dev/ansible-control-host-configure.sh &> {{ logs_dir }}/ansible/ansible-control-host-configure"
        executable: /bin/bash

    - name: Run host-configure test harness
      import_role:
        name: host-configure-test-harness
        tasks_from: run
      environment:
        FAIL2BAN_ENABLED: "{{ fail2ban_enabled | default(false) }}"
        CI_NETWORK_ENGINE: "{{ ci_network_engine | default('default') }}"
