---
- name: Ensure /etc/hosts is configured
  hosts: seed-hypervisor:seed:overcloud:infra-vms:ansible-control
  max_fail_percentage: >-
    {{ etc_hosts_max_fail_percentage |
       default(host_configure_max_fail_percentage) |
       default(kayobe_max_fail_percentage) |
       default(100) }}
  tags:
    - etc-hosts
  tasks:
    - import_role:
        name: etc-hosts
