---
- name: Update host packages
  hosts: seed-hypervisor:seed:overcloud:infra-vms
  vars:
    # Optionally set this to a list of packages to update. Default behaviour is
    # to update all packages.
    host_package_update_packages: "*"
    host_package_update_security: false
  tasks:
    - name: Update host packages
      dnf:
        name: "{{ host_package_update_packages }}"
        security: "{{ host_package_update_security | bool }}"
        state: latest
      when: ansible_facts.os_family == 'RedHat'
      become: true
