---
# Deploy/pull/reconfigure/stop/upgrade inspection data store.
#
# Follows kolla-ansible service deployment patterns.
#
# Variables:
# action: One of deploy, destroy, pull, reconfigure, upgrade

- name: Ensure inspection store is deployed
  hosts: controllers[0]
  tags:
    - inspection-store
  roles:
    - role: inspection-store
      inspection_store_action: "{{ kayobe_action }}"
      inspection_store_enabled: "{{ inspector_store_enabled }}"
      inspection_store_port: "{{ inspector_store_port }}"
      inspection_store_config_path: "{{ config_path }}/inspection-store"
