---
- name: Configure tuned profile
  hosts: seed:seed-hypervisor:overcloud:infra-vms
  max_fail_percentage: >-
    {{ tuned_max_fail_percentage |
       default(host_configure_max_fail_percentage) |
       default(kayobe_max_fail_percentage) |
       default(100) }}
  tags:
    - tuned
  roles:
    - role: giovtorres.tuned
      become: true
      when:
        - tuned_active_builtin_profile != ""
