---
- project:
    queue: kayobe
    templates:
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-py39:
            #NOTE(wszumski): We have dropped python3.9 support, so disable this job.
            files: THIS-JOB-IS-DISABLED
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-rocky9
        - kayobe-overcloud-centos9s
        - kayobe-overcloud-ubuntu-noble
        - kayobe-overcloud-tls-rocky9
        - kayobe-overcloud-host-configure-rocky9
        - kayobe-overcloud-host-configure-centos9s
        - kayobe-overcloud-host-configure-ubuntu-noble
        - kayobe-overcloud-upgrade-rocky9
        - kayobe-overcloud-upgrade-ubuntu-jammy
        - kayobe-seed-rocky9
        - kayobe-seed-ubuntu-noble
        - kayobe-seed-upgrade-rocky9
        - kayobe-seed-upgrade-ubuntu-jammy
        - kayobe-seed-vm-rocky9
        - kayobe-seed-vm-ubuntu-noble
        - kayobe-infra-vm-rocky9
        - kayobe-infra-vm-ubuntu-noble
    gate:
      jobs:
        - openstack-tox-py39:
            #NOTE(wszumski): We have dropped python3.9 support, so disable this job.
            files: THIS-JOB-IS-DISABLED
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-rocky9
        - kayobe-overcloud-ubuntu-noble
        - kayobe-overcloud-tls-rocky9
        - kayobe-overcloud-host-configure-rocky9
        - kayobe-overcloud-host-configure-ubuntu-noble
        - kayobe-overcloud-upgrade-rocky9
        - kayobe-overcloud-upgrade-ubuntu-jammy
        - kayobe-seed-rocky9
        - kayobe-seed-ubuntu-noble
        - kayobe-seed-upgrade-rocky9
        - kayobe-seed-upgrade-ubuntu-jammy
        - kayobe-seed-vm-rocky9
        - kayobe-seed-vm-ubuntu-noble
        - kayobe-infra-vm-rocky9
        - kayobe-infra-vm-ubuntu-noble

    experimental:
      jobs:
        - kayobe-seed-images-centos9s
        - kayobe-seed-images-rocky9
        - kayobe-seed-images-ubuntu-noble
        - kayobe-seed-vm-centos9s-q35
        - kayobe-seed-vm-rocky9-q35
        - kayobe-seed-vm-ubuntu-noble-q35
