---
- project:
    queue: kayobe
    templates:
      - openstack-cover-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-rocky9
        - kayobe-overcloud-centos9s
        - kayobe-overcloud-ubuntu-jammy
        - kayobe-overcloud-tls-rocky9
        - kayobe-overcloud-host-configure-rocky9
        - kayobe-overcloud-host-configure-centos9s
        - kayobe-overcloud-host-configure-ubuntu-jammy
        - kayobe-overcloud-upgrade-rocky9
        - kayobe-overcloud-upgrade-ubuntu-jammy
        - kayobe-overcloud-upgrade-slurp-rocky9:
            voting: false
        - kayobe-overcloud-upgrade-slurp-ubuntu-jammy:
            voting: false
        - kayobe-seed-rocky9
        - kayobe-seed-ubuntu-jammy
        - kayobe-seed-images-rocky9
        - kayobe-seed-upgrade-rocky9
        - kayobe-seed-upgrade-ubuntu-jammy
        - kayobe-seed-upgrade-slurp-rocky9
        - kayobe-seed-upgrade-slurp-ubuntu-jammy
        - kayobe-seed-vm-rocky9
        - kayobe-seed-vm-rocky9-efi
        - kayobe-seed-vm-ubuntu-jammy
        - kayobe-seed-vm-ubuntu-jammy-efi
        - kayobe-infra-vm-rocky9
        - kayobe-infra-vm-ubuntu-jammy
        - openstack-tox-pep8
        - openstack-tox-py39
        - openstack-tox-py310
        - openstack-tox-py311
    gate:
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-rocky9
        - kayobe-overcloud-ubuntu-jammy
        - kayobe-overcloud-tls-rocky9
        - kayobe-overcloud-host-configure-rocky9
        - kayobe-overcloud-host-configure-ubuntu-jammy
        - kayobe-overcloud-upgrade-rocky9
        - kayobe-overcloud-upgrade-ubuntu-jammy
        - kayobe-seed-rocky9
        - kayobe-seed-ubuntu-jammy
        - kayobe-seed-upgrade-rocky9
        - kayobe-seed-upgrade-ubuntu-jammy
        - kayobe-seed-upgrade-slurp-rocky9
        - kayobe-seed-upgrade-slurp-ubuntu-jammy
        - kayobe-seed-vm-rocky9
        - kayobe-seed-vm-ubuntu-jammy
        - kayobe-infra-vm-rocky9
        - kayobe-infra-vm-ubuntu-jammy

    experimental:
      jobs:
        - kayobe-seed-images-centos9s
        - kayobe-seed-images-ubuntu-jammy
