---
- project:
    queue: kayobe
    templates:
      - ansible-role-jobs
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-ubuntu-noble
        - kayobe-overcloud-ubuntu-noble-podman
        - kayobe-overcloud-host-configure-rocky9
        - kayobe-overcloud-host-configure-ubuntu-noble
        - kayobe-overcloud-upgrade-ubuntu-noble
        - kayobe-seed-rocky9
        - kayobe-seed-rocky9-podman
        - kayobe-seed-ubuntu-noble
        - kayobe-seed-ubuntu-noble-podman
        - kayobe-seed-upgrade-rocky9
        - kayobe-seed-upgrade-ubuntu-noble
        - kayobe-seed-vm-rocky9:
            voting: false
        - kayobe-seed-vm-rocky9-efi:
            voting: false
        - kayobe-seed-vm-ubuntu-noble
        - kayobe-seed-vm-ubuntu-noble-efi
        - kayobe-infra-vm-rocky9:
            voting: false
        - kayobe-infra-vm-ubuntu-noble
    gate:
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-ubuntu-noble
        - kayobe-overcloud-ubuntu-noble-podman
        - kayobe-overcloud-host-configure-rocky9
        - kayobe-overcloud-host-configure-ubuntu-noble
        - kayobe-overcloud-upgrade-ubuntu-noble
        - kayobe-seed-rocky9
        - kayobe-seed-rocky9-podman
        - kayobe-seed-ubuntu-noble
        - kayobe-seed-ubuntu-noble-podman
        - kayobe-seed-upgrade-rocky9
        - kayobe-seed-upgrade-ubuntu-noble
        - kayobe-seed-vm-ubuntu-noble
        - kayobe-infra-vm-ubuntu-noble

    experimental:
      jobs:
        - kayobe-overcloud-centos9s
        - kayobe-overcloud-host-configure-centos9s
        - kayobe-overcloud-rocky9
        - kayobe-overcloud-rocky9-podman
        - kayobe-overcloud-tls-rocky9
        - kayobe-overcloud-upgrade-rocky9
        - kayobe-seed-images-centos9s
        - kayobe-seed-images-rocky9
        - kayobe-seed-images-rocky9-podman
        - kayobe-seed-images-ubuntu-noble
        - kayobe-seed-images-ubuntu-noble-podman
