---
- project:
    queue: kolla
    templates:
      - ansible-role-jobs
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-py310:
            #NOTE(wszumski): We have dropped python3.10 support, so disable this job.
            files: THIS-JOB-IS-DISABLED
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-infra-vm-rocky10
        - kayobe-infra-vm-ubuntu-noble
        - kayobe-overcloud-host-configure-rocky10
        - kayobe-overcloud-host-configure-ubuntu-noble
        - kayobe-overcloud-rocky10
        - kayobe-overcloud-rocky10-podman
        - kayobe-overcloud-tls-rocky10
        - kayobe-overcloud-ubuntu-noble
        - kayobe-overcloud-ubuntu-noble-podman
        - kayobe-overcloud-upgrade-ubuntu-noble
        - kayobe-seed-rocky10
        - kayobe-seed-rocky10-podman
        - kayobe-seed-ubuntu-noble
        - kayobe-seed-ubuntu-noble-podman
        - kayobe-seed-upgrade-ubuntu-noble
        - kayobe-seed-vm-rocky10
        - kayobe-seed-vm-ubuntu-noble
    gate:
      jobs:
        - openstack-tox-py310:
            #NOTE(wszumski): We have dropped python3.10 support, so disable this job.
            files: THIS-JOB-IS-DISABLED
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-infra-vm-rocky10
        - kayobe-infra-vm-ubuntu-noble
        - kayobe-overcloud-host-configure-rocky10
        - kayobe-overcloud-host-configure-ubuntu-noble
        - kayobe-overcloud-rocky10
        - kayobe-overcloud-rocky10-podman
        - kayobe-overcloud-tls-rocky10
        - kayobe-overcloud-ubuntu-noble
        - kayobe-overcloud-ubuntu-noble-podman
        - kayobe-overcloud-upgrade-ubuntu-noble
        - kayobe-seed-rocky10
        - kayobe-seed-rocky10-podman
        - kayobe-seed-ubuntu-noble
        - kayobe-seed-ubuntu-noble-podman
        - kayobe-seed-upgrade-ubuntu-noble
        - kayobe-seed-vm-rocky10
        - kayobe-seed-vm-ubuntu-noble

    experimental:
      jobs:
        - kayobe-infra-vm-centos10s
        - kayobe-infra-vm-centos10s-cloud-image
        - kayobe-infra-vm-rocky10-cloud-image
        - kayobe-infra-vm-ubuntu-noble-cloud-image
        - kayobe-overcloud-centos10s
        - kayobe-overcloud-tls-centos10s
        - kayobe-overcloud-upgrade-rocky10
        - kayobe-seed-centos10s
        - kayobe-seed-images-centos10s
        - kayobe-seed-images-rocky10
        - kayobe-seed-images-rocky10-podman
        - kayobe-seed-images-ubuntu-noble
        - kayobe-seed-images-ubuntu-noble-podman
        - kayobe-seed-upgrade-rocky10
        - kayobe-seed-vm-centos10s
        - kayobe-seed-vm-centos10s-cloud-image
        - kayobe-seed-vm-centos10s-q35
        - kayobe-seed-vm-rocky10-cloud-image
        - kayobe-seed-vm-rocky10-q35
        - kayobe-seed-vm-ubuntu-noble-cloud-image
        - kayobe-seed-vm-ubuntu-noble-q35
